import type { NextPage } from "next";
import Head from "next/head";
import { Suspense } from "react";
import { OrbitControls, Environment, Plane } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { Female } from "../components/Models/Female";
import Link from "next/link";

const FemaleRig: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rigging Model Female</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="buttongroup">
        <Link href="/">
          <button className="button">Male</button>
        </Link>
      </div>
      <main>
        <Canvas camera={{ position: [2, 2, 5] }}>
          <OrbitControls />
          <Environment preset="warehouse" />
          <Suspense fallback={null}>
            <Female scale={7} position-y={-2.4} />
          </Suspense>
          <Plane scale={40} rotation-x={-Math.PI * 0.5} position-y={-2.4} />
        </Canvas>
      </main>
    </>
  );
};

export default FemaleRig;
