import type { NextPage } from "next";
import Head from "next/head";
import { Suspense } from "react";
import { OrbitControls, Environment, Plane } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { Male } from "../components/Models/Male";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rigging Model</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <video className="video" autoPlay loop muted playsInline>
        <source src="./test2.mp4" />
      </video>
      <div className="buttongroup">
        <Link href="/femalerig" className="button">
          <button className="button">Female</button>
        </Link>
      </div>
      
      <canvas id="drawing-canvas" height="128" width="128"></canvas>
      <main>
        <Canvas camera={{ position: [2, 2, 5] }}>
          <OrbitControls
            makeDefault
            minPolarAngle={0}
            maxPolarAngle={Math.PI / 1.75}
          />

          <Environment preset="warehouse" />
          <Suspense fallback={null}>
            <Male scale={30.9} position-y={-2.4} />
          </Suspense>
          {/* <Plane scale={40} rotation-x={-Math.PI * 0.5} position-y={-2.4} /> */}
        </Canvas>
      </main>
    </>
  );
};

export default Home;
